jobs:
  include:
    - stage: "Documentation"
      julia:
        - nightly
        - release
        - 1.1
      matrix:
        allow_failures:
          - julia: nightly
      notifications:
        email: true
      os:
        - linux
        - osx
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
