language: julia
os: linux
julia: release
notifications:
  email: true
script:
  - julia --project -e 'using Pkg; Pkg.test("StructuralDDP", coverage=true)'
after_success:
  - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
  - julia --project=docs/ docs/make.jl
  - julia --project -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
