language: julia
os: linux
julia: 1.1
notifications:
  email: true
jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      name: "HTML"
      after_success: skip
    - stage: "Test"
      julia: 1.1
      os: linux
      script:
        - julia --project -e 'using Pkg; Pkg.test("StructuralDDP")'
      after_success: skip
