language: julia
os: osx
julia: 1.1
notifications:
  email: true
script:
  - julia -e 'Pkg.clone(pwd())'
  - julia -e julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("PkgName")); include(joinpath("docs", "make.jl"))'
after_success: skip
